version: "3.8"

networks:
    laravel:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16

volumes:
    dbdata:
        driver: local

services:
    nginx:
        image: nginx:1.18.0-alpine
        ports:
            - "29080:80"
        volumes:
            - .:/var/www/html
            - ./infrastructure/webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - postgres
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: infrastructure/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
            - ./infrastructure/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - laravel
        depends_on:
            - postgres
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        extra_hosts:
            - host.docker.internal:host-gateway

    postgres:
        image: postgres:13.4
        ports:
            - "${DB_OUTER_PORT}:5432"
        volumes:
            - "./infrastructure/db:/docker-entrypoint-initdb.d"
        # volumes:
        #     - dbdata:/var/lib/mysql
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            # POSTGRES_DB: upakovali_online
            POSTGRES_MULTIPLE_DATABASES: "${DB_DATABASE},upakovali_online_db_test"
        networks:
            - laravel

    node:
        image: node:15-alpine3.10
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
        environment:
            - MH_STORAGE=maildir
        ports:
            - "29025:8025"
            - "29026:1025"

#    workers:
#        build:
#            context: .
#            dockerfile: infrastructure/Dockerfile
#            # target: infrastructure/workers
#            target: workers
#        volumes:
#            - .:/var/www/html
#        depends_on:
#            - postgres
